### ISSUE TITLE
[FEAT]: Blog - Creating a Blog Post #46

### ISSUE THREAD

**Issue by AdelakunShola** [hngprojects/hng_boilerplate_php_laravel_web#51]
> ## Description
> * Develop an API endpoint that allows only a super admin to create a blog post.
> 
> ## Purpose
> * The purpose of the endpoint is for a super admin to be able to create a blog post.
> 
> ## The Blog Schema
> ![blog drawio](https://private-user-images.githubusercontent.com/35671277/349277227-e48e4938-1c09-4d44-b442-a28d72d2e380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzMyNDcsIm5iZiI6MTcyMTQzMjk0NywicGF0aCI6Ii8zNTY3MTI3Ny8zNDkyNzcyMjctZTQ4ZTQ5MzgtMWMwOS00ZDQ0LWI0NDItYTI4ZDcyZDJlMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIzNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNTZjODExZWE3OWM0ZTQ2MmU5YmUzNWUwNjhkZjMwMTZkMDA1MTI2NzA4MzhhZWQ3NTgyMzk0NzM0NzVkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Af_6_fRvx9uwBOnTzrSKZi9Qg4QErxOtzxIp484g4xc)
> 
> ## Acceptance Criteria
> 1. The endpoint allows only a super admin to create a blog post.
> 2. A valid token with the super admin role is supplied to the Authorization header.
> 3. If no Authorization header is supplied or an invalid token is supplied, the error should return a status code of 401.
> 4. If the token does not have the admin role, the error should return a status code of 403.
> 5. Returns a 200 OK status code and the correct response body when the blog is created successfully.
> 
> ## Endpoints
> ### Create Blog [POST] `/api/v1/blogs`
> 1. A valid token is supplied to the Authorization header
>    
>    * If no Authorization header is supplied or an invalid token is supplied, the error should return a status code of 401
> 
> **Request Header** `{ "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR..." }`
> 
> 2. A valid request body with correct validation is supplied:
>    
>    * The title field cannot be empty
>    * The content field cannot be empty and should be rich text
>    * The error should return a status code of 400 if the required fields are missing
> 
> **Request Body**
> 
> ```
>        {
>            "title": "Blog Title",     // required
>            "content": "<p>First paragraph.</p><p>Second paragraph.</p>",     // required, rich text
>            "tags": ["tag1", "tag2", ...],    //optional
>            "image_urls": ["Image URL 1", "Image URL 2", ...]    // optional, can be inserted in the content
>        }
> ```
> 
> #### Successful Response
> **Status Code 201**
> 
> ```
>    {
>        "status_code": 201,
>        "message": String,
>        "data": {
>              "blog_id": String,
>              "title": String,
>              "content": Text,
>              "image_urls": [String],
>              "tags": [String],
>              "author": String,
>              "created_at": Date 
>        }
>    }
> ```
> 
> #### Error Responses
> **Status Code 400**
> 
> ```
>    {
>        "message": String,
>        "status_code": 400
>    }
> ```
> 
> **Status Code 401**
> 
> ```
>    {
>        "message": String,
>        "status_code": 401
>    }
> ```
> 
> **Status Code 403**
> 
> ```
>    {
>        "message": String,
>        "status_code": 403
>    }
> ```
> 
> **Status Code 500**
> 
> ```
>    {
>        "message": String,
>        "status_code": 500
>    }
> ```
> 
> ## Testing
> 1. Unit tests
> 
> * Test for valid authorization token in the header
> * Test for invalid authorization token
> * Test for authorization token expiry time
> * Test that the invalid requests body, e.g. test for each required field, returns the appropriate status codes and data
> * Test that the valid request body returns the valid status code and data

**Comment by AdelakunShola** [comment]
Slack id: Harry

This issue is linked to an already approved issue [link](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/46)

**Comment by bamo100** [comment]
good day, have you implemented this functionality?

**Comment by AdelakunShola** [comment]
@bamo100 Not yet, I'm waiting for the roles and permission table.
